### ISSUE TITLE
fixing current tests bug

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/PVNet#243] opened 2024-08-06 17:33 UTC
<img width="949" alt="Screenshot 2024-08-06 at 23 03 07" src="https://github.com/user-attachments/assets/33d5de91-ebbe-4b35-b2b6-4a1fc7dfd0e2">

**Comment by AUdaltsova** [comment] 2024-08-06 18:04
Ok so I don't know why this test didn't trip up the previous merge, it should have (when I roll back to the versions at merge locally, it happens as well), but here's what I found out: the problem is that me adding the new keys to ocf_datapipes/ocf_datapipes/batch/batches.py somehow messes with the right batch keys getting assigned to the right tensors from pre-saved test batches. This data was supposed to have this key: satellite_t0_idx, which would've been fine. I bet if I go comment out the new keys in the failing PR it will pass this test

**Comment by AUdaltsova** [comment] 2024-08-06 18:54
Yep that 100% on me, I stuck new keys in the middle of an enumerated class. The test is fine

**Comment by peterdudfield** [comment] 2024-08-07 06:03
No problem @AUdaltsova, it happens. 

Yea we have had this problem before with Enums. Something to think about in the future for `ocf_data_samples` - https://github.com/openclimatefix/ocf-data-sampler/issues/7


probably a few options
1. Open up current batches, and load with old enums, and save with new enums. 
2. try moving the new wind enums to the end of the Batch, and then hopefully all the others are in the correct order. I know this breaks the nice grouping of variables

I'd probably be tempted to do 2., but up to you

**Comment by AUdaltsova** [comment] 2024-08-07 07:18
@peterdudfield yes I thought the same https://github.com/openclimatefix/ocf_datapipes/pull/351

**Closed** 2024-08-07 11:17 UTC
